### PR TITLE
elemental2-20190325 is outdated when use j2cl-master

### PR DESCRIPTION
**Pull request by swuecho**

### CODE REVIEW

**Comment by realityforge** [comment]
Where did you get this version? I suspect it is a `-SNAPSHOT` version released by vertispan? In which case you either update to a more recent version of the snapshot. I believe the fix was applied ~11 days ago and thus any snapshot after that should work. Be warned that the vertispan variant includes changes that do not appear in the google variant.

Alternatively you can use the google variant either from the source repository (If you are using Bazel) or I have published a version to Maven central at https://mvnrepository.com/artifact/org.realityforge.com.google.jsinterop/base/1.0.0-b2-e6d791f

**Comment by niloc132** [comment]
I'm not sure how it can be something from us - the `http_archive` rule will always download from `https://github.com/google/...` as shown in the link.

But if a fix was applied 11 days ago to google/elemental2, it would not be in `https://github.com/google/elemental2/archive/v20190325.zip` at all, you'd need to use `master` as described, or wait for another tag to be published, right?

---

That said, yes there is no reason to use Vertispan elemental2 builds even when building from maven (though to my knowledge you still must use our jsinterop-base fork, as I'm not aware of another jsinterop-base available from maven which works in j2cl).

**Comment by realityforge** [comment]
Eep - it seems I crossed issues - I thought @swuecho was referring to a maven artifact. Ignore my comment.

@niloc132 When I deploy the `base` artifact I also deploy a j2cl variant with and `artifactId` of `base-j2cl` rather than `base. So for the artifact:

https://mvnrepository.com/artifact/org.realityforge.com.google.jsinterop/base/1.0.0-b2-e6d791f

there is the j2cl compatible variant at

https://mvnrepository.com/artifact/org.realityforge.com.google.jsinterop/base-j2cl/1.0.0-b2-e6d791f

In the next week or two, I plan to do another release but it will follow the same pattern as this.

**Comment by jDramaix** [comment]
LGTM. With db1173af71db2270df09ffa584ece5449d3a472f it's now ok to use the master version of the repo with j2cl.

**Pull request closed without merging**
