### PR TITLE
Add WebGL constants to integer entities

### PR DESCRIPTION
**Pull request by zbynek**
Proposed solution for #149

### CODE REVIEW

**Comment by jDramaix** [comment]
LGTM. Thanks for the patch.
I'm importing your change internally and it will be submitted soon.

**Comment by zbynek** [comment]
@jDramaix thanks for merging this! Are there any `jar`s compiled from the master branch published to some repository or should I wait for a release?

**Comment by zbynek** [comment]
@jDramaix any news on the release?

**Comment by jDramaix** [comment]
Yep I'm fine doing a 1.2.0. I'll try to release it asap

**Pull request closed without merging**
