### PR TITLE
Move to the OSS version of mediakeys.js externs

### PR DESCRIPTION
**Pull request by realityforge**
Minor changes exist in the variant included with closure-compiler
around the init structs passed to the events but this seems unlikely
to break downstream user code.

### CODE REVIEW

**Comment by jDramaix** [comment]
Thanks

**Comment by jDramaix** [comment]
I think w3c_clipboardevent.js is now available in OSS repo so we can switch to the oss version (not in this PR)

**Comment by realityforge** [comment]
I believe that `w3c_clipboardevent.js` will be relatively easy to cut across. The differences between the modern closure externs and the one in elemental2 is minimal. I will tackle that in due course. The `svg.js` seems like it has had more extensive surgery in closure compiler since the copy was into elemental2 so that may require a smidge more work .. but definitely doable.

**Comment by jDramaix** [comment]
I created a patch internally for using oss versions of `w3c_clipboardevent.js` and `svg.js`
It should be submitted soon

**Pull request closed without merging**
