### PR TITLE
Add an explicit parameter name for event handlers

### PR DESCRIPTION
**Pull request by realityforge**

### CODE REVIEW

**Comment by gkdn** [comment]
Thanks for the patch but I think need to be smarter about this instead of manually maintaining a long list of parameter names.

@jDramaix IIUC, your suggestion was choosing name based on method name. Method names are not very helpful for good parameter name and in case of multiple parameter we are back to square one. I think we can get by naming it based on the parameter's type. We should still fallback to counter but that would be only the case of more than one param of the same type. WDYT?

**Comment by realityforge** [comment]
That could work for many types. Most of those events in this PR are typed `{!Event}` and thus would work quite nicely. Some like `elemental2.dom.WebSocket.OnmessageFn.onInvoke.p0` are parameterized types but you could still extract the base type (in that scenario it would be [`MessageType`](https://github.com/google/closure-compiler/blob/master/externs/browser/html5.js#L2988).

However I feel there is a lot of scenarios where you would still want to name the parameters with better semantic names. And some cases that may require surgery to the closure externs to get any names in place (i.e. type union parameters and record type parameters in particular). And it is unclear what if any value you get from non Object/instance types.

On the other hand this list is relatively easy to maintain too. I only intended to rename ~3 of the WebSocket ones but found it was super easy so did the rest. It was a result of basically running a command something like

```sh
> bazel build //java/elemental2/dom:all 2>&1 | grep "WARNING: We generated a default name for parameter " | awk '{print $9}' | sort | uniq > tmp/Output.txt
```

And then regexing out all the event handlers which didn't take long.

**Comment by gkdn** [comment]
> However I feel there is a lot of scenarios where you would still want to name the parameters with better semantic names. 

I agree. We would still have the same functionality to change then names and we will continue doing that. This is just for having a better default.

**Comment by jDramaix** [comment]
> @jDramaix IIUC, your suggestion was choosing name based on method name. Method names are not very helpful for good parameter name and in case of multiple parameter we are back to square one. I  think we can get by naming it based on the parameter's type. We should still fallback to counter but that would be only the case of more than one param of the same type. WDYT?

That sounds good to me. Let me implement that and take a look in the generated code if it's acceptable or not.

**Comment by realityforge** [comment]
It seems this is not the desired direction for the project so closing the PR off for now

**Pull request closed without merging**
