### PR TITLE
Maven layout

### PR DESCRIPTION
**Pull request by realityforge**
Enhance the `./build_gwt_mvn_jars.sh` script so that it takes a mandatory version parameter and it outputs the elemental2 jars out into maven2 compatible directory structure and generates the required poms.

This is a suggested solution for https://github.com/google/elemental2/issues/46

### CODE REVIEW

**Comment by niloc132** [comment]
Thoughts on going another step and scripting up the `mvn install`/`mvn deploy` commands? In our fork, I've also modified this file [0] (to pipe `yes` at `mv`, I assumed it was deliberately used in the original over `cp`, and to make `bazel` an env var so CI can swap in a different binary easily without it being on the path) and created poms [1], but configured the poms to attach the artifacts while being deployed (so that existing deployment wiring can understand the poms as the full project). 

I don't imagine that this is optimal yet either, but it does make our jenkins for internal deployments very simple:
 * `${BAZEL} clean --expunge` (since otherwise "snapshot" artifacts are erroneously cached by bazel)
 * `${BAZEL} build //java/...` (likely not needed in light of the next command)
 * `./build_gwt_mvn_jars.sh maven`
 * Built-in `mvn clean install` support, and deploying those artifacts (with build info) to associated artifactory repo

[0] https://github.com/Vertispan/elemental2/blob/master/build_gwt_mvn_jars.sh
[1] https://github.com/Vertispan/elemental2/blob/master/maven/core/pom.xml#L40

**Comment by realityforge** [comment]
I have added in the BAZEL environment variable. 

However I avoided adding `mv install` as I was under the impression that this is largely equivalent to `./build_gwt_mvn_jars.sh ~/.m2/repository/ MyVersion` - or am I mistaken? One thing I had considered was swapping the order of parameters to `./build_gwt_mvn_jars.sh` so version is first and if the path is not specified then defaulting it to the local maven cache directory (i.e. `~/.m2/repository`). Thoughts?

As to the deploy - I actually have an unchecked in variant of the script that does a deploy ... but does it through raw curl, raw gpg and a little bit of ruby. I had set it up so that I could in theory deploy them to maven central under a group such as `org.realityforge.com.google.elemental2` until this project starts making regular releases. I could try to set it up so that there is no requirement on ruby (although that would mean people would need to click a button if releasing to Maven central.

**Comment by niloc132** [comment]
You might well be right - I've been burned in the past by assuming this though, so I tend to actually prefer running `install` or `install:install-file` in case there are other metadata items that need to be deployed too. Local .m2/repository vs remote SNAPSHOT vs remote releases each seem to have slightly different setup.

As you can see from our fork, I'm deploying internally similarly with a custom groupid, hoping to start pushing publicly very soon. Would you consider putting your curl/gpg/ruby stuff in your script so we can see about comparing more directly? I don't like the 2x size that my extra build wiring requires, but I do rather like how much simple it makes the build process (both for simple CI and also for new users hoping to make small changes/improvements and share their results).

**Comment by tbroyer** [comment]
Fwiw, see https://github.com/google/google-java-format/pull/273#issuecomment-380930947

**Comment by jDramaix** [comment]
First, thanks for taking care of this!
Internally I have template for each pom file that I use for releasing. I can add them to the opensource repo.
I've also a script for building the jar files (similar to what build_gwt_mvn_jar.sh is doing) and uploading them to sonatype. We don't  use build_gwt_mvn_jar.sh internally so feel free to modify it to fit the open source community needs. If @tbroyer or @niloc132 or any other gwt contributor give their LGTM it's ok for me.

Note that in the long term I'd like to have only one script that I can use for releasing from the opensource repository and not from the internal one.

That being said, I think If we could use the bazel rule introduced by @ronshapiro  in google/bazel-common@2782531 It would be nice. Do you think you could give it a try?

**Comment by realityforge** [comment]
It would be better to use the bazel rule so I will give that a whirl and update the PR as required.

**Comment by jDramaix** [comment]
I've opensource'd my scripts to build and release elemental. I think the scripts need to be modified in order to deploy the jars locally.

**Comment by niloc132** [comment]
Yeah, the newly added scripts in here and jsinterop-generator will need some updates to be more flexible:
 * support local deployment
 * support parameterized repos so snapshots are an option (don't only allow deployments to sonatype, allow `repositoryId` and `url` to be provided by calling code)
 * support skipping gpg, or at least don't mandate putting the on the command line so `ps` etc can pick them out

The first will be handy for local deployments, but one or both of the others will be necessary to avoid every fork also forking jsinterop-base, and editing WORKSPACE, scripts in order to just push a build somewhere it can be used.

**Comment by jDramaix** [comment]
yes! I won't do the work as I don't work with maven anymore but I would be happy to review any contributions to these scripts.

**Comment by realityforge** [comment]
Closing this as out of date

**Pull request closed without merging**
