### PR TITLE
added es6_proxy.js, w3c_pointerlock.js and w3c_gamepad.js externs

### PR DESCRIPTION
**Pull request by treblereel**

### CODE REVIEW

**Comment by gkdn** [comment]
@mollyibot Could you generate an internal elemental2 diff for review? Pls send it to @jDramaix as well.

**Comment by treblereel** [comment]
@gkdn please let me know if there any issues

**Comment by gkdn** [comment]
@treblereel Have you looked/played with the code generated for es6_proxy? Was it usable for your use case?

**Comment by treblereel** [comment]
> @treblereel Have you looked/played with the code generated for es6_proxy? Was it usable for your use case?

yeap, it works well. I use it in my DI (https://github.com/crysknife-io/crysknife) with `goog.reflect.objectProperty` to intercept requests to bean property inject points.

**Comment by gkdn** [comment]
LGTM minus the things that needs to be marked as `int`. @mollyibot could you add those as comments?

**Comment by treblereel** [comment]
@mollyibot done

**Comment by gkdn** [comment]
@mollyibot let's bring the patch to google3. You can use github_import.sh

**Pull request closed without merging**
