### PR TITLE
Move to using upstream externs for Selection API

### PR DESCRIPTION
**Pull request by realityforge**
This relies on google/closure-compiler#3370 being merged
which includes all the stnadardized Selection API in a
separate extern.

### CODE REVIEW

**Comment by jDramaix** [comment]
Thanks Peter! Great job!

**Comment by jDramaix** [comment]
I think I can now import that change

**Comment by realityforge** [comment]
@jDramaix This should be ready to apply

**Comment by realityforge** [comment]
Oops - I sent this comment from the tram and it seems you had already replied ;) The web page hadn't updated till I got to the office ;)

**Pull request closed without merging**
